CREATE TABLE [dbo].[Plant]
(
	[IdPlant] INT NOT NULL IDENTITY, 
    [ComName] VARCHAR(64) NOT NULL, 
    [ScienName] VARCHAR(64) NOT NULL, 
    [Picture] NVARCHAR(250) NOT NULL, 
    [Height] VARCHAR(32) NULL, 
    [Type] VARCHAR(32) NOT NULL, 
    [NeedLight] VARCHAR(32) NOT NULL, 
    [PlantTime] DATE NULL, 
    [HarvTime] DATE NULL, 
    [Description] NVARCHAR(MAX) NOT NULL, 
    [FavPlant] NVARCHAR(MAX) NULL, 
    [AvoidPlant] NVARCHAR(MAX) NULL, 
    [IdSpecies] INT NOT NULL, 
    [IdCare] INT NULL, 
    [IdExposure] INT NOT NULL, 
    CONSTRAINT [PK_Plant] PRIMARY KEY CLUSTERED([IdPlant] ASC),
    CONSTRAINT [FK_Plant_ToSpecies] FOREIGN KEY ([IdSpecies]) REFERENCES [dbo].[Species] ([IdSpecies]),
    CONSTRAINT [FK_Plant_ToCare] FOREIGN KEY ([IdCare]) REFERENCES [dbo].[Care] ([IdCare]),
	CONSTRAINT [FK_Plant_ToExposure] FOREIGN KEY ([IdExposure]) REFERENCES [dbo].[Exposure] ([IdExposure]),
	CONSTRAINT UK_Plant_ComName UNIQUE ([ComName]),
	CONSTRAINT UK_Plant_ScienName UNIQUE ([ScienName]),
	CONSTRAINT UK_Plant_Picture UNIQUE ([Picture]),
);